apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RMph8rYp2kEFSbpxEvTFn1JKeJ4OOg++zksrJXzw+mfHe+9/,iv:5z94nRpqV2pHrqCd/dtiNHmgVFsSxPD2NjAkXOHF0Zg=,tag:4BeeAG7yead2RyEzPrRCDg==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZpsaT0wdCNmRu39qZegEuDBY/8TKVb3Pl+9XX0u0VmpLiIqqYpCElQFTg3AhVkJH0zrDFb2Cxr8rprrMJLlu8H/e2ATCkkylXm4rDMOih5Uo+X88PZCHAeQwH0yA7ek484mlr8iBLGwyt8JMIGcwMHQ4xgcY7/GLusMO6Kg5voAu2RcoU75wPIlviD7Au3bsU+V3bkz4P7STP6actrkzLej4fGs9JfsXZXSt4BYwvw==,iv:Xhza8rOQv2sU5jA2an2cGyBoWH+qBuYpJpl6nn2O8QY=,tag:QSLRjrbqzuIKGDgbby9ZvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRkNhTmlpZXowU29vc2Yx
            S0srUE1KaWpndEJONmxsckMzZC8wTjhzbjNFCnlRaHJPaXhnZloydTExSXVrTVRK
            TGg1b2kzMlM3NkFqTWJCZ1EvSGE0STAKLS0tIFlUWGY1UGc5ZUEySDZQRXBIUGlO
            bS9TY0J2ZVhWdjJqMGV2Tk0zVFlTUVUKGBhCon5XABsP5nYs52iCxqHjXo1MxWS5
            QIK6QTfdSKTm8vscR5QxTl7fFgADhhwPnwjs35trdyE0+DQtkwIFJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T07:15:32Z"
    mac: ENC[AES256_GCM,data:EnPatLF8dN9EEGZDS+mcuu/JYl5ZSKbZ6Lo2A8HZV0nX0l7CpifhA7pMQLNKl+V+BT+4C/GK84v9jGM2v/k+KMpf+tUeUgaFwTycMIdavYMyBi3HuSRtUDTt2pRRsdzJAkX2bPFGlG2qz649W9J2oXNq2kLQ+NNtuuw7rx1VrQM=,iv:sYOK0ZBDC1OHONVE8NMgeNXtVtddeWt+VbjOxI6WIW0=,tag:TiFJ27O1IBryI9uWVO32qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
