apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:po3eF7AnjLgc7YhazRM9/lhE7HWplq8iuidxN80nJxlbcXhJ,iv:GszJ2D2sOWuVGljAzsS+zvXAAJFSKj/h6uAsER1uEDc=,tag:NQ3aUpy8fOhTrhPPrXBRAw==,type:str]
    credentials.json: ENC[AES256_GCM,data:2hdYObZuA9gBsIdJMVsqpcCaIL2wy/wBL0yoMvSrk0DDVHXLmMtizunTYb4ZPfsweVJV2H9gTdsq2u2By7yepIH7IjCM2CKg3wqvyswzYSAS1SkiW6RI81CH1p7o73MQ0BnTVqOL3kEs8bcWNq5vWLZ9PW8PIhuO04/t1yBqepMTAKhMyR64a0MBnrz8hNEVqu60n/eiOj3lFVzzPTkyESFxP6vfpiquhcaUS8KZXw==,iv:NWr8Ludi7mn7xBwT+f6exfRIegnUPHi0suQCa4tD5Mo=,tag:5tJ8IpXn6j3LM+vsy24P8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieTFPa2Fld2VXWWJlekY1
            M0dFY2M4bU5wamU3Q0xwQ0J2MjZWcVpJSmo4CjU5T3R0eTU4VjlpZVlySFlQTjFK
            N3o4N0F6Nzl6bU9pUWdWcVN1cm43aVEKLS0tIFFaMjQ3bkRqT1QraEU4U2hFMzlQ
            ampjY0xKR0doSVZmQWUyVDJoWXVGSlEKMxARvZZ8kuWdUG6OMWkJTp2GRL36Zvyj
            ojk5mhf3DA1A0aXZb1EenucVWS4623Rs5cu9I1vvwZbHHPvghg7ing==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:37:23Z"
    mac: ENC[AES256_GCM,data:qLhRSXZ2RZKAVqQ+R+Dn1mPFjlaKGkwntduY85Bpwq2+SqJSpMR9gFYTDrW2ZHMpLAZfMLnXbE6uFlzQSObGFwdTWISKBrlF1hlmbw/mtVCI/4k7r7+l2PgpRBGbH92oZoQLQnMTbIHAtu2Y3VVeEjM1x4lYUsGae8Au/EZi9NU=,iv:w4ZN4kt0md3rw6ZmOeVYM6C8B4dd+SVMNEHXX1NSV0k=,tag:bpsriqP0bWrtIt8PIHDxFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
