apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:odE/tS5+qbFj2CQWXn9Dl3McZ5e5oMK+,iv:c+/8yEIsMSiM6jX0N479Aj2J2qNcXQSTljeZUlQ4Nfk=,tag:6W/av9rxANGKltOGENfyoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NnhkbFdjZ3ZHMS9NaVN4
            ZGdSRE5PTGJFWHhTOEEzeVplVEJRUmlRbUJJCitySHV6OVZEanhMcE9lTWhIU3dn
            M3o3bHkyQVJNNVBObmhGOS9aTldRYXMKLS0tIEtWVmMrTi9GWWdFN1Y2d1N3V3dq
            Ync5RWdGbFdPdDRGQ2F6bGhKWWNmR2MKgvHGbx+daq+LvkExUMw5v6Q3tML4rUCl
            V7lzgDcsFLo5cq5EfyOxYSLPBJt0RQk0cUEzQxSzTzZRQPHVDRZRcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T20:18:54Z"
    mac: ENC[AES256_GCM,data:upUYHW9E36AS0sTEAWMaLQ3aBulSA/uWpAOdbXqeA20YsKlMhr3hRVduZnCFfxwlBuexBuElTftaHLd1bD17dxGs/KhnQD4hPLtxz9KAJUGilmIL0g5Z71JXOpdO8BfX3z/ND07H1vePZxShYAQbh8OlG/PTb2mmm8sVnCeHRRs=,iv:A9xgzodgQolqbBxWi9SgInTf5YoE+D6c5dvG2VcWUf4=,tag:T3lmYk20GqLww8bliTetwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
