apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:u5/EeKI=,iv:Rc92mmYGkX2oJB8gV6O0Zg1zvF1PfmpAS3edDxwTR/Q=,tag:AB7vPvfVXPHXQMy44FSy+g==,type:str]
    admin-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDdPTnN5L2ozY0h0S0NF
            K1kvRk9RTk56SHhkbFluWXN0N3JCeFoxeDJzCjhUVys4UDkyOEkwL3JaODlMRnVR
            djh0M2tEQ0o2WDZrSWNFYnd4amh1TkEKLS0tIEJuVUZDQ3ZySFgzcnVHZitlNHNK
            MU5LSnFkRWduOElaNFdCRm5LSlo1QkUKNkDJVVx3yzoOWnZlESiHUAu+alhfJloV
            C/bWNTRDaub1qfKnCo6J53pmZ8vtYs7Z7jSXQTA2iTDpB8jtsdTCGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T20:18:54Z"
    mac: ENC[AES256_GCM,data:l+KLAuzASVkiFDIc1MT0yNI+q9GgbA5AqawbUTmtdI3IBaZxv06BN4LmqQUaQf+FAAw6hjefI8YONAE6TDkdE2yvmDaDMwaYEM4wWAKejGjtZfW7AeHdx/lIWaPgaDk5p1G7XiUdCkhSX+vj3oNyOCrLrVDpDwHH7YnndLWKBwY=,iv:KRfT1JGAx3yVmLpEzn9qdkKna0p13XHoh2lCc8alFRI=,tag:7V00VO5xa5BHk9tXUzXzKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
