apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:G9DD8EB5bDYKIIJwpeE+Fhj3QxWzy6dO8ItaYw+pVFipO9ngpNDRtQ==,iv:tQRPFc3gRd1ne6u2kClp8Xh+w9T2DP2S2guBejrSaac=,tag:bDefXSx+H24ybBTwsHezpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTmt3dFZiRFJ6SXN5S2dh
            WVl2TVI2REU3Z1VNYzVNRDVNbzdPbDRtY2pNCmgzYnd5Q1lDUUlmUmtoQnc2VlNQ
            My9YVTkyeXRubTdvV1dOMXhvTzJzVWMKLS0tIFVhckIwRjk1cjZGTXpnT1BsSjlP
            NjNMR2VvRUNtWEhMYXIyeHFKdk9rTmMK8Z1HNsiaWAFSmoqWp0oRRwPzSI47JomF
            oN2JMahEIOotyHari8wZfSq59m7b3hwXJepA7QpMOztpfEa+wyC/2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T08:17:21Z"
    mac: ENC[AES256_GCM,data:BWZaLRetfv3yFyl8Ouav50WlfIpimiwjw4nedQX5GRqvvdrg8h3Ot6EvjpfqgIqx4G+KV8SoK9hjUaMKQD2oqdC01jsvSSbBafELH958z1f7nAUdQHmJ1OeQ4HEycFzfCiAjgmiX/Q9esGF5xREakCuEgdiK7opIU40noneRBg8=,iv:O66b4wKSJpzcw/s/0RDmIPEZL1Talag7aFsYNskAdac=,tag:Waah2fs7CWVcR6k82w3VCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
