apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:i+dxUmblEgYBIdVTp2NwiDNrBA14wm4/Ns8yhrIPf8LmdmtNS1FSTA==,iv:6ZKx6B3LdHvuYAmPBMu4jayKm2KsUpO2VtQr90ZBl1o=,tag:M+3Bps2W5vp8Bc7H7LK+Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL2hVRG1sOVRwSkNLMmhn
            T2NoRVhldE9XQjFnTE9TZ1RaeC9BVW8xaEg4ClZkM0RPalZ1T3RpM25hL2puaWx3
            eVZoQ1VsTk1xQXppKzdtY1AzU0oxZjAKLS0tIElaTDNNaWpnc0VnanpXMS9jK2Zr
            MEN1Tm5LQVNHTVVqNjBGSWxxbnhpaVUKzB3l6+yxm/jWAyrji2Bm+n8xgVpJ7ukX
            +Lt6GhD9/MiMcTF6OwvRnjtS6ECZ/s/EeycwP8oO6zTMuXGF/d6yRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T03:51:01Z"
    mac: ENC[AES256_GCM,data:+C3RUAqxcYeVTTaHepeMCm49th5cgUBqOhTQD9GrwW4mtAkGo9eyo4ln34KeZVqEm5QfFXQgbk/WU++YdLRD3zWKnOXWoIlHIHbThGKLWPtiDVwltA8ofkqdLALBPaKiMsEjb06Rh6CG2zUpLBpA8okXh0gdeSSo+aYM+SDgVSA=,iv:QBtj7wuBuRiZk8TSYlMLp9bojVt0FxsYrR+nVauEpIs=,tag:MnhGrUIW+gKff8JvZqWlMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
