---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-containers
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-containers-arm64
    githubConfigUrl: https://github.com/granth7/containers
    minRunners: 1
    maxRunners: 2
    containerMode:
      type: dind
    # template:
    #   spec:
    #     containers:
    #       - name: runner
    #         image: ghcr.io/granth7/actions-runner:2.314.0@sha256:394533d7753a3c3c585bd47b9ba7a5cde663af54580edaecb14e6c9bfa1fae17
    #         command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-secret
      valuesKey: github_token
      targetPath: githubConfigSecret.github_token
