apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nxVngRYN7nw/7iJvLDXq8ns=,iv:5DwfOrxWs/SbvaftkdiHAdMnZaHD5JCjBgg0PqUd2eQ=,tag:6b0kdU5ErKV9C6jyzAFoBg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zZipDV/jmBpI6BfOYVy5znPwKpVe9drVuD9FIGVqfg56QDjA,iv:rv/UJqc9Eb7txlTyDY+v3nBhNxNyKb4xegOchfF97kE=,tag:TqJlrcPm4fjEZelFuQr2WQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:PsXEezRy/bT2Jtc=,iv:LFTRfDlWU0Sb1CpIroNw4N+hsOkG09kyz2erC4pXkXY=,tag:Lf9fbEqqwSbAo0abxGQMlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMGdBOHFxRHRqRU5qSm5M
            Y0xiakc5Y3JueEZEeHpQd2I2Q3BkQkI3WEQ4CmIxTEo5bHpOSHNDUVl5Vk45Um9P
            clJ3TTFYeGM0c0wxelNIRjdEb3JPcjgKLS0tIGdtcXhMaWRzWlhORHdwTXluRERj
            QzUvY3c3U3l1eFZLeVF3WXFDZTBldnMK2LNYcCXbNyMbTqjbw7d9gbtyvovNfyw4
            TKWBPIWH/E5R9FeYgEQi3DjqKzAT4OA2lqwpzoU3RFp3mb2g+0AVjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T00:11:40Z"
    mac: ENC[AES256_GCM,data:UAqBZ2a/Kd9rQrF0+uzP/FmFowl4hasRz9q3Ehe4RSuS3O9RmcF7CldqluCYt0xzG8liQrYz7BQrSzPe/VDwYc8hEOhFXo4m7AiCIpfPWT16tFNrKuFWVQK/W+cWJMyaDecYyi2GEfoxHbR7sfpW3BnClO3dmpYOoOlobOqrn/E=,iv:DeBpf9t4Xp6/O7lSmjjpkRWh3uMZ+99BJt4vxm7OH5E=,tag:eVrdTisf/dky5T01Rk5pJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
