apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vG/P3oyuggC611U=,iv:0IylQpFAHOMZhxXWuMOdCh4RfJFvsI3RvbOKzpP/Pto=,tag:scGbeeooVvlwEbGvv24Ang==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mrpeumZmXWuNzDwngo+bxMA=,iv:018svUywBf5yaLFzWlrktjul9L/pYYj4BSgsoT49skk=,tag:YUqxN02hAgvE1YMFUHl/qQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rTWVMkErFxspUEAeVOTEW9mawXm7kKHKnQdk+K4nHVuG2n7F,iv:xyOaLb/ZXU6JoaR69/LODuBd/2eYj/jc9AL7ovy3zik=,tag:qTRN5szGTVrxQgF3ziYcaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVWlZMFYwNzlOend3RTdx
            d0MwRmpEYlpFVGwzUmdhRklPbmduM0dVRkFnCnJnb3F3VkRhOFRKZ1Q0Z2JsL3hn
            NkNkV1pNVWRuQ1pjbHducEZmc1N0bTgKLS0tIFltRDFIZzQ1UmNZTy9tRFlQaXhB
            UjdEeXJSZjBBYk83d2Y0UUxtU0d0bVEKkDPfxBOes/ZVQmrn6y4XBzR2nsBy7vCo
            Qtwb2wAKC34N39E8yf9TLDoJmPKNuQt/DTMvmbQGmIvWGLN4eprM5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:37:23Z"
    mac: ENC[AES256_GCM,data:mUp0YJbd9kN8YTqxMYQjcNFkSl975qVP5cviRy0ONjckObflKEPc1mQGQhtkg0Ib9n1aLFdJZsid7fIB2pgJU/Ex9oIcNNBtMwEfBVAoUjPMu2riEjeGBwN79tGpqi7AVZmWvYd+QPBckGj78hGfmbQx8qg4DmBwjSJkA9f1SB8=,iv:1sGmMGE6Xu2qLOHoG4CypqOT3TV11buPCEqwxSnh73s=,tag:H5MHU2U3E182p6ryfG3kQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
