apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gUfGv/Dj31MgL24=,iv:5mK6fp/jXjCrl/aMnkLmekRM6MgU6VJMQBC5UObF1+Q=,tag:foEjBUyLHtZ9Omn34UAu9A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Szb1RDu9ia7IcF5y2pJj8Gc=,iv:PNW56Jry9gV7YVxuwie/uNHcW1WpMjGWKBa5ngv8CC0=,tag:sE+Yv958ZATTELefY8qBwQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IDdrwGJO7SUgrtd+aTo1UUGK3XU8UkPD1aritCMgcSJddwBc,iv:zfafgozGuFHcncTcLNJkitpDDpCcMfqLfKNy+jomw4o=,tag:HP/oFa2RtHWvh0PQk3zMJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYkNBL0h5OUdQMTdMUVdC
            UFFoT0VmcE5QYklFR1VkNllEWG5hbFFZOXlnCjFMVjIxUm5oU082T01xRUlIVVJX
            Nmc4KysrQzhhcDJIZEJwYjY3bTFxZEkKLS0tIDIvZi9uZXQ3bndYY2tmQWk3ZjYv
            QldCbXVnVDBzUkNuUE1Wa05VQjNLN0kKMlA07Ny//kM64fmRHqCNo+g4xxqtnbyi
            ZX8DnjPyZAy/nhZE+S1iLeKs3sqGAnLx64sbV0sy4XWWdurGQD2UvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T08:17:21Z"
    mac: ENC[AES256_GCM,data:1pOkXlNJyEIzR8/GQGQI+As7DDI7redc9LNaZ0JvPgz5h4I9N+E3egjACVp6EFr6GVGN2xo+1hL6UrH7Q1iUyFMgZ55Fj8dvrP4FeogiJ9jKx6p149i78xr7pBg9Ja9sunhYai/WUQd02KHSlWNmGvw0u+Cgp0tAhwqAQ/5gQ8Y=,iv:iGxONBiIeBUBBzWm6dPzAfBsVz8gHXG7ShIY3Aqe5HA=,tag:Qw8f/Nddr8NkfgD2ddFiiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
