apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:GrKTFfL4Ctk+Lvsy2kXL49WzZ3NFOG4wbmaFf7kpDxI=,iv:PXczVYvVoY2s1OTK/3WISxeqTKvhQtbfho2v7VwuAmY=,tag:BRCKqcsKNCGbAnEIbCMXeQ==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:0rqZkEzPz71YLjqvrfYoM4NoNj83Q71ON64fxtTwiSg+xJXt,iv:DmWafFLXIQ+uXGsIUt7wANkF3WbWxSW9+I5leDYvNog=,tag:W6Gg1YD12t7ap7b8fZqkww==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:VObKNCJaU5jSOqSqOqmmGb4v2CVX0UIY3dfQPBkLSsCYd3fgvTIdeg==,iv:CATOlCF2FcE0Ziq4jUe9HXE4kqlH0dZYkxCGSoJ1gKQ=,tag:qF8taDmQtMInTriDd3b3Ug==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:RCD2JPI=,iv:CuMypggRDY/Hy45YzSKtGtG57A/f5SBMPJilGy5VAuk=,tag:5xTNuqTQ/xHEFeeN+dbMxQ==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdnVmSEJhWWZiNTZkMU8y
            ME5BTFB6YWJ4V29KVDR4R09pSklEOGR2S0dNCnBUcW9UVFM4Nzc3QWJKNTJWSlV5
            d1I0QThjVmNnc1dNLzlSd1ZjTzJ5UFkKLS0tIHNSL3RabitvL3ZCR2Mxc29BUis2
            bVo1QUJVbHFlLzFyd1VNa1lrLzU2dEUKuEANikL/IPWBQQlnNqhAqYcg2z5RWeXe
            GfE95D5Yk683UYXD+p6ykc56llxvXRDkrx87Zofd7YaXRcaEos2IlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:37:22Z"
    mac: ENC[AES256_GCM,data:AYv8slqRDhDMGukp+i1pobMhsz0LD2LET6a3kUwekcqkFZ0csHuffvPHSMwRl8DUp27Wj2h4Q0Das6ktK1Ws0MS+76abJPlpiBqcj/2pLSCUj0/WtXA8A6aunCMdzceypvVEWVMIibRXs4nDVkX4qjJNZ+BJ55DeySKo384mlIk=,iv:7dBUglh0ML+pzlOTPr+D80DF3oJ8OQWjS+i1CVRIPus=,tag:EdilhisrBA001VpvPp4zPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
