apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZvYRhx4wbs4rvf8Y1vmupptjM/lYuG0qyCvYxZWvtWH3eR6RzYg5EQ==,iv:ttHacCpB/Pwy1ky/fEpuP4QSlKHe1IfcH/csb78p/vY=,tag:89WueD8v77rOqBqVSLCw9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUk56emhJUC9uTkNTN3dj
            alN2Qms0a2lTTWpHc21yZ0pMSkdxZ1kxL1hRCjFHanozbGkxbVBHdzNVTFRPUEFq
            dlh6WU9VQTg0djY0cHJKMUNpdXVTRkkKLS0tIHhZYkNrOUEwU3F3VGo2a3IxbUtk
            MXhpbmtwWUZYRHFtN25vY3EvbDhsY2cKuHupykU7gwBypj9H8auuI15K91wA0Te5
            JokvPrjrc7nXo6al8PWihK/lATZH/lq1UfMsd6BdCOvyrK5+9aAYlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:37:23Z"
    mac: ENC[AES256_GCM,data:eHDoKRZz1X9UmFgKZMsdg7ZUZEzkMCxodmEUoncAPAMu1pbNcUodFFvZ0mBLnorFpDMe54qGDD1yzKLP+ny9mgAYyQFjcsDfSK5NZlEolFhK5j+4HX8Yasfe12xkgtYcFDzaqNI8wzC1FF0kK2LD7Qpva1GGioZ04vPgA81+8I8=,iv:BVmeZ23HwCFqgApfO3u1j8Vur/pE2Bahf0LIFh6vhz8=,tag:bCgtdHSqzLDW98/LRqZhbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
