apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ouGE+G5bmFXMKtUKLGZyzeDsSsQx0C4GuOTvSz1MFWK8CkHbhbIaYA==,iv:FulD7UHscBI7+HztZV8OO/IKmgXaXbHoOvwPXOmFkj4=,tag:H2g2Gf0pOKf+xWBD6eEKjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m05s89q9guefzjj6qc7whjaq8g7ejcjy6ctqzpcgfa2xsl6t83cqamlmpp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeTdMMWlINmErMlUwcjdC
            dVBIY2xYSGR1YUtFSVVhZDN0dUxpVlpKR0VFCnJPb0lRMlFkeGhLbEV6ditoVEMv
            M3M4VGFMRDhuR0lmSTV6Qm9OcEo5MzAKLS0tIGRRUWRsQldRcDhWSVlBYmhzUW5Y
            MVV0Zk94STdqVUd2cDhMTXNranJ5ZFEKF64WNFIGl5HxTUPRiMWEcFHFf2h2f6Lg
            7TNnsLyRnu93mUjSTO7Zsw8CZ18hpY2LkndJ04vdv36NN4EYZZyO0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T20:18:54Z"
    mac: ENC[AES256_GCM,data:VuWNaPPHX9FONht2UAd4LaamJy189pIvJLNO2slVLmR5tlwNC3Vamo83/3rCuh6y4Ni2uKzOu7Q5Zdfp36na/HdxC3WRjt4OY5HuBAC+ILl9gILqjfmmM1ieIGf2GiUGPhVWYNLpMX8XPO6mkl+n7KtpRn2AKPq1r8T0aWnnpdY=,iv:RHvwLZ70e+W20m8KF4CeleDfwopT+R80S1qzbGuP5PY=,tag:hXOYcuSmVYUI+4h5joFxaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
